### ISSUE TITLE
any update

### ISSUE THREAD

**Issue by halukmy** [sfera-labs/arduino-lora-net#1]
coming soon?

**Comment by giampiero7** [comment]
Hi halukmy,
Is there any feature missing you are looking for?

**Comment by halukmy** [comment]
@giampiero7 first of all, i want so much thanks for this beatiful repo,

1.st is, can you share so much simple sample for repo( more simplfy than iono :) , i can help about it we can build together https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaDuplex/LoRaDuplex.ino on it,


second question about, addressing, you mean 0-250 slave units, so is it possible on grouped units?

for example 20 watermeters are same addresssing and send message grouping with that addressing?

and third ,   Iono.subscribeDigital(DO1, 0, &IonoLoRaLocalSlave::subscribeCallback);
  slave.process();
what are these units? i so happy if you can explaint,
thanks much

**Comment by giampiero7** [comment]
Hi @halukmy ,
Thanks for the appreciation!
Unfortunately I don't have a simpler example ready to share.
The repo you linked uses the same master-slave and 1-byte addressing scheme of this one. On this one you have some security layers on top of it and no need for a constant poll from the master.
Try starting from the Iono example and remove pieces to understand how it works.

If you use the same address for multiple slave units you will create conflicts and wouldn't be able to discern data from one unit or another.
Do you need more that 249 slave units?

About subscribeDigital() and process() you can read here:
https://github.com/sfera-labs/iono/wiki/Iono
